pollme/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('polls/', include('polls.urls', namespace="polls")),
    path('quiz/', include('quiz.urls', namespace="quiz")),

]

quiz/urls.py
from django.urls import path
from . import views

app_name = "quiz"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:myid>/", views.quiz, name="quiz"),
    path('<int:myid>/data/', views.quiz_data_view, name='quiz-data'),
    path('<int:myid>/save/', views.save_quiz_view, name='quiz-save'),
    path('add_quiz/', views.add_quiz, name='add_quiz'),    
    path('add_question/', views.add_question, name='add_question'),  
    path('add_options/<int:myid>/', views.add_options, name='add_options'), 
    path('results/', views.results, name='results'),    
    path('delete_question/<int:myid>/', views.delete_question, name='delete_question'),  
    path('delete_result/<int:myid>/', views.delete_result, name='delete_result'),
    path('fileupload/',views.fileup,name='fileupload'),
    path('display/',views.displaypdf,name='displaypdf'),
    path('displaymccp/',views.displaypdfmccp,name='displaypdfmccp'),
    path('displaydm/',views.displaypdfdm,name='displaypdfdm'),
    path('displayos/',views.displaypdfos,name='displaypdfos'),
    path('displaywt/',views.displaypdfwt,name='displaypdfwt'),
    path('displayai/',views.displaypdfai,name='displaypdfai'),
    path('notes/',views.notes,name='notes'),


]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
import random


class StudentFormq(models.Model):
    sub=[('MCCP','MCCP'),('AI','AI'),('DM','DM'),('OS','OS'),('WT','WT')]
    subject=models.CharField(max_length=10,choices=sub,null=True)
    firstname = models.CharField("Enter unit name", max_length=50)  
    file      = models.FileField() # for creating file input



class Quiz(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)    
    number_of_questions = models.IntegerField(default=1)
    time = models.IntegerField(help_text="Duration of the quiz in seconds", default="1")
    
    def __str__(self):
        return self.name

    def get_questions(self):
        return self.question_set.all()
    
class Question(models.Model):
    content = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content
    
    def get_answers(self):
        return self.answer_set.all()
    
    
class Answer(models.Model):
    content = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"question: {self.question.content}, answer: {self.content}, correct: {self.correct}"
    
class Marks_Of_User(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()
    
    def __str__(self):
        return str(self.quiz)

quiz/forms.py
from django import forms
from .models import Quiz, Question,Answer,StudentFormq
from django.contrib import admin

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('name', 'description', 'number_of_questions', 'time')

    
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('content', 'quiz')
        
class StudentForm(forms.ModelForm): 
    class Meta:  
        model = StudentFormq 
        fields = "__all__"

quiz/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.shortcuts import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import QuizForm, QuestionForm,StudentForm
from .models import *
from django.forms import inlineformset_factory
from django.contrib import messages
from django.http import HttpResponse
from .function import handle_uploaded_file_ai,handle_uploaded_file_dm,handle_uploaded_file_os,handle_uploaded_file_wt,handle_uploaded_file_mccp
import os


def notes(request):
    return render(request,"quiz/notes.html")

def displaypdf(request):
    return render(request,'quiz/sub.html')

def displaypdfmccp(request):
    path=(r"C:\Users\Tejaswi\Desktop\Poll-App (1) (1)\Poll-App (1)\quiz\static\upload\MCCP")
    pdf_list =os.listdir(path)   
    return render(request, 'quiz/MCCP_notes.html', {'pdfs': pdf_list})

def displaypdfdm(request):
    path=(r"C:\Users\Tejaswi\Desktop\Poll-App (1) (1)\Poll-App (1)\quiz\static\upload\DM")
    pdf_list =os.listdir(path)   
    return render(request, 'quiz/DM_notes.html', {'pdfs': pdf_list})

def displaypdfos(request):
    path=(r"C:\Users\Tejaswi\Desktop\Poll-App (1) (1)\Poll-App (1)\quiz\static\upload\OS")
    pdf_list =os.listdir(path)   
    return render(request, 'quiz/OS_notes.html', {'pdfs': pdf_list})

def displaypdfwt(request):
    path=(r"C:\Users\Tejaswi\Desktop\Poll-App (1) (1)\Poll-App (1)\quiz\static\upload\WT")
    pdf_list =os.listdir(path)   
    return render(request, 'quiz/WT_notes.html', {'pdfs': pdf_list})

def displaypdfai(request):
    path=(r"C:\Users\Tejaswi\Desktop\Poll-App (1) (1)\Poll-App (1)\quiz\static\upload\AI")
    pdf_list =os.listdir(path)   
    return render(request, 'quiz/AI_notes.html', {'pdfs': pdf_list})

def fileup(request):
    if request.user.has_perm('polls.add_poll'):
        if request.method == 'POST':  
            student = StudentForm(request.POST, request.FILES)  
            s1=request.POST['firstname']
            x=request.POST['subject']
            if student.is_valid():
                if x=='MCCP':
                    handle_uploaded_file_mccp(request.FILES['file'],s1)  
                    model_instance = student.save(commit=False)
                    model_instance.save()
                    return HttpResponse("File uploaded successfuly<br><a href='\'>BACK</a> ")
                elif x=='OS':
                    handle_uploaded_file_os(request.FILES['file'],s1)  
                    model_instance = student.save(commit=False)
                    model_instance.save()
                    return HttpResponse("File uploaded successfuly<br><a href='\'>BACK</a> ")
                elif x=='WT':
                    handle_uploaded_file_wt(request.FILES['file'],s1)  
                    model_instance = student.save(commit=False)
                    model_instance.save()
                    return HttpResponse("File uploaded successfuly<br><a href='\'>BACK</a> ")
                elif x=='AI':
                    handle_uploaded_file_ai(request.FILES['file'],s1)  
                    model_instance = student.save(commit=False)
                    model_instance.save()
                    return HttpResponse("File uploaded successfuly<br><a href='\'>BACK</a> ")
                elif x=='DM':
                    handle_uploaded_file_dm(request.FILES['file'],s1)  
                    model_instance = student.save(commit=False)
                    model_instance.save()
                    return HttpResponse("File uploaded successfuly<br><a href='\'>BACK</a> ")
                  
        else:  
            student=StudentForm()  
            return render(request,"quiz/fileupload.html",{'form':student})
    else:
        return HttpResponse("<div style='top:20px'><center><h2>Sorry but you don't have permission to do that!</h2> <a href='/'>go</a></center></div>")

def index(request):
    quiz = Quiz.objects.all()
    para = {'quiz' : quiz}
    return render(request, "quiz/index.html", para)

@login_required
def quiz(request, myid):
    quiz = Quiz.objects.get(id=myid)
    return render(request, "quiz/quiz.html", {'quiz':quiz})

def quiz_data_view(request, myid):
    quiz = Quiz.objects.get(id=myid)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.content)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


def save_quiz_view(request, myid):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
    
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(content=k)
            questions.append(question)

        user = request.user
        quiz = Quiz.objects.get(id=myid)

        score = 0
        marks = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.content)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.content:
                        if a.correct:
                            score += 1
                            correct_answer = a.content
                    else:
                        if a.correct:
                            correct_answer = a.content

                marks.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                marks.append({str(q): 'not answered'})
     
        Marks_Of_User.objects.create(quiz=quiz, user=user, score=score)
        
        return JsonResponse({'passed': True, 'score': score, 'marks': marks})

def add_quiz(request):
    if request.method=="POST":
        form = QuizForm(data=request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.save()
            # obj = form.instance
            # return render(request, "quiz/add_quiz.html", {'obj':obj})
            return redirect('quiz:index')
    else:
        form=QuizForm()
    return render(request, "quiz/add_quiz.html", {'form':form})

def add_question(request):
    questions = Question.objects.all()
    questions = Question.objects.filter().order_by('-id')
    if request.method=="POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'quiz/add_question.html')
    else:
        form=QuestionForm()
    return render(request, "quiz/add_question.html", {'form':form, 'questions':questions})

def delete_question(request, myid):
    question = Question.objects.get(id=myid)
    # if request.method == "POST":
    question.delete()
    return redirect('quiz:add_question')
    # return render(request, "quiz/delete_question.html", {'question':question})


def add_options(request, myid):
    question = Question.objects.get(id=myid)
    QuestionFormSet = inlineformset_factory(Question, Answer, fields=('content','correct', 'question'), extra=4)
    if request.method=="POST":
        formset = QuestionFormSet(request.POST, instance=question)
        if formset.is_valid():
            formset.save()
            alert = True
            return render(request, "quiz/add_options.html", {'alert':alert})
    else:
        formset=QuestionFormSet(instance=question)
    return render(request, "quiz/add_options.html", {'formset':formset, 'question':question})

def results(request):
    marks = Marks_Of_User.objects.all()
    return render(request, "quiz/results.html", {'marks':marks})

def delete_result(request, myid):
    marks = Marks_Of_User.objects.get(id=myid)
    # if request.method == "POST":
    marks.delete()
    return redirect("quiz:results")

quiz/templates/quiz/AI_notes.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
                style="
        height: 697px;">
                <a href="{% url 'quiz:displaypdfai' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">AI</span></a>

                <a href="{% url 'quiz:displaypdfwt' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">WT</span> </a>

                <a href="{% url 'quiz:displaypdfos' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">OS</span></a>

                <a href="{% url 'quiz:displaypdfdm' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">DM</span></a>

                <a href="{% url 'quiz:displaypdfmccp' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">MCCP</span></a>

                <hr />
            </div>
        </div>
        <div class="col py-3">
            <center>
                {% for pdf in pdfs %}
                <div class="ok">
            <h3>{{pdf}}</h3>
            <iframe src="/static/upload/AI/{{pdf}}" width="800" height="500"><br>
            </iframe><br><br>
            </div>
            {% endfor %}
            </center>
        </div>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/MCCP_notes.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
                style="
        height: 697px;">
                <a href="{% url 'quiz:displaypdfai' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">AI</span></a>

                <a href="{% url 'quiz:displaypdfwt' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">WT</span> </a>

                <a href="{% url 'quiz:displaypdfos' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">OS</span></a>

                <a href="{% url 'quiz:displaypdfdm' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">DM</span></a>

                <a href="{% url 'quiz:displaypdfmccp' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">MCCP</span></a>

                <hr />
            </div>
        </div>
        <div class="col py-3">
            <center>
                {% for pdf in pdfs %}
                <div class="ok">
            <h3>{{pdf}}</h3>
            <iframe src="/static/upload/MCCP/{{pdf}}" width="800" height="500"><br>
            </iframe><br><br>
            </div>
            {% endfor %}
            </center>
        </div>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/OS_notes.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
                style="
        height: 697px;">
                <a href="{% url 'quiz:displaypdfai' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">AI</span></a>

                <a href="{% url 'quiz:displaypdfwt' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">WT</span> </a>

                <a href="{% url 'quiz:displaypdfos' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">OS</span></a>

                <a href="{% url 'quiz:displaypdfdm' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">DM</span></a>

                <a href="{% url 'quiz:displaypdfmccp' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">MCCP</span></a>

                <hr />
            </div>
        </div>
        <div class="col py-3">
            <center>
                {% for pdf in pdfs %}
                <div class="ok">
            <h3>{{pdf}}</h3>
            <iframe src="/static/upload/OS/{{pdf}}" width="800" height="500"><br>
            </iframe><br><br>
            </div>
            {% endfor %}
            </center>
        </div>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/WT_notes.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
                style="
        height: 697px;">
                <a href="{% url 'quiz:displaypdfai' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">AI</span></a>

                <a href="{% url 'quiz:displaypdfwt' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">WT</span> </a>

                <a href="{% url 'quiz:displaypdfos' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">OS</span></a>

                <a href="{% url 'quiz:displaypdfdm' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">DM</span></a>

                <a href="{% url 'quiz:displaypdfmccp' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">MCCP</span></a>

                <hr />
            </div>
        </div>
        <div class="col py-3">
            <center>
                {% for pdf in pdfs %}
                <div class="ok">
            <h3>{{pdf}}</h3>
            <iframe src="/static/upload/WT/{{pdf}}" width="800" height="500"><br>
            </iframe><br><br>
            </div>
            {% endfor %}
            </center>
        </div>
    </div>
</div>
{% endblock %}

quiz/templates/quiz/add_question.html
{% extends 'baseq.html' %}
{% block title %} Add Question {% endblock %}

{% block body %}
<style>
  th,td{
    padding:10px; 
  }
  
</style>
<div class="container mt-4">
  <form action="{% url 'quiz:add_question' %}" method="POST"> {% csrf_token %}
    <table>
      <th>
        <td>{{ form.as_table }}</td>
      </th>

      </table><br>
    &nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-info">Submit</button>
  </form>
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>Question</th>
        <th>Quiz</th>
        <th>Delete</th>
      </tr>
    </thead>
    {% for question in questions %}
    <tr>
      <td><a href="{% url 'quiz:add_options' question.id %}">{{question.content}}</a></td>
      <td>{{question.quiz}}</td>
      <td><a href="{% url 'quiz:delete_question' question.id %}" class="btn btn-danger">Delete</a></td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

quiz/templates/quiz/add_quiz.html
{% extends 'baseq.html' %}
{% block title %} Add Quiz {% endblock %}

{% block body %}
<style>
    th,td{
    padding:10px; 
  }
  
</style>
<div class="container mt-4">
    <form action="{% url 'quiz:add_quiz' %}" method="POST"> {% csrf_token %}
    <table>
        <th>
            <tr>{{ form.as_table }}</tr>
        </th>
    </table>
    <br><button type="submit" class="btn btn-info">Submit</button>
</form>
</div>
{% endblock %}

quiz/templates/quiz/delete_question.html
{% extends 'baseq.html' %}
{% block title %} Delete Question {% endblock %}

{% block body %}
<div class="container mt-4">
    <h4>Are you sure you want to delete {{question.content}}</h4>
    <br>
    <form action="" method="POST">
            
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'quiz:add_question' %}">Cancel</a>
    
        <input class="btn btn-danger" type="submit" value="Delete">
    </form>
</div>

{% endblock %}

quiz/templates/quiz/delete_result.html
{% extends 'base.html' %}
{% block title %} Delete Results {% endblock %}

{% block body %}
<div class="container mt-4">
    <h4>Are you sure you want to delete {{marks.user}} who has score: {{marks.score}} in {{marks.quiz}} ?</h4>
    <br>
    <form action="" method="POST">
            
        {% csrf_token %}
        <a class="btn btn-warning" href="{% url 'quiz:result' %}">Cancel</a>
    
        <input class="btn btn-danger" type="submit" value="Delete">
    </form>
</div>

{% endblock %}

quiz/templates/quiz/fileupload.html
{% extends 'base.html' %}

{% block content %}
<p><h1>File Upload</h1></p><br>
<div class="answerbox">
<form method="POST" class="post-form" enctype="multipart/form-data">  
        {% csrf_token %}  
        <table><th><td>{{ form.as_table}}  </td></th>     </table>
        <a href="{% url 'quiz:notes' %}" class="saves btn btn-default">
                <button type="submit" class="saves btn btn-default">Back</button>
        </a>
        <button type="submit" class="save btn btn-default">Save</button><br><br>    
</form>  
</div>
<style>
        *{
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
    text-align: center;
    font-size: 20px;
  
}
.answerbox
{
height: 50%; /*Specify Height*/
width:  35%; /*Specify Width*/
/*Add 1px solid border, use any color you want*/
align-items: center;
margin: auto;
display: block;
display: grid;
justify-content: center;
transform: translate(4%, 0%);
box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset;
text-align:center; /*Align the text to the center*/
}
h1{
        margin-top: 8%;
        
}
.save{
        margin-left: 10%;
}

.post-form{
        margin: auto;
       
}
th,td{
                padding:15px; 
         }

        
        button{
    color: #ffffff;
    border-radius: 30px;
    padding: 10px 15px;
    background: linear-gradient(122.33deg, #68bed1 30.62%, #1E94E9 100%);
    margin-top: 30px;
    margin-bottom: 10px;
    font-size: 16px;
    transition: all 0.3s linear;
}

button:hover{
        background-image: linear-gradient(to right, #25aae1, #4481eb, #04befe, #3f86ed);
    box-shadow: 0 4px 15px 0 rgba(65, 132, 234, 0.75);
}
</style>
{% endblock %}

quiz/templates/quiz/login.html
{% extends 'baseq.html' %}
{% block title %} Login Page {% endblock %}
{% block css %}
<style>
      .head1 {
    color: #FBAD30;
    font-size: 2rem;
    font-weight: bold;
    height: 50px;
  }

  .head2 {
    color: #EF4926;
    font-size: 2rem;
    font-weight: bold;
  }
  </style>
  {% endblock %}

  {% block body %}
  <div class="row py-5 p-4 bg-white rounded shadow-sm">

    <div class="col-lg-6">
        <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold"
            style="color:black;font-weight:bold">Login Details</div>
        <br>
        <form class="row g-4" method="POST" action="/login/">{% csrf_token %}
            <div class="col-md-12">
                <label for="inputname" class="form-label" style="font-weight: bold;"><i>
                        Username</i></label>
                <input type="text" placeholder="Enter Username" style="text-align: center;"
                    class="form-control" id="username" name="username" required>
            </div>

            <div class="col-md-12">
                <label for="inputname" class="form-label" style="font-weight: bold;"><i>
                        Password</i></label>
                <input type="password" placeholder="Enter Password" style="text-align: center;"
                    class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
      
  {% endblock %}

quiz/templates/quiz/notes.html
{% extends 'base.html' %}

{% block content %}
<style>
    body{
            background-image: url('/static/images/note.jpg');
            background-position:center;
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
    }
    .container{
        padding-top: 15%;
        padding-left: 60%;
    }
    .btn-info{
        width: 100%;
        
    }
</style>

<div class="container">
    {% if user.is_superuser %}
    <a class="btn btn-primary" href="{% url 'quiz:fileupload' %}" role="button"><h3>Upload</h3></a>
    {% endif %}<br><br><br><br>
    <a class="btn btn-primary" href="{% url 'quiz:displaypdf' %}" role="button"><h3>Display</h3></a>

</div>

{% endblock %}

quiz/templates/quiz/results.html
{% extends 'baseq.html' %}
{% block title %} Results {% endblock %}

{% block body %}
<div class="container mt-4">
      <br>
      <table class="table">
        <thead>
          <tr>
            <th>User</th>
            <th>Quiz</th>
            <th>Score</th>
            <th>Delete</th>
          </tr>
        </thead>
{% for mark in marks %}
<tr>
  <td>{{mark.user}}</td>
  <td>{{mark.quiz}}</td>
  <td>{{mark.score}}</td>
  <td><a href="{% url 'quiz:delete_result' mark.id %}" class="btn btn-danger">Delete</a></td>
</tr>
{% endfor %}
</table>
</div>
{% endblock %}

quiz/templates/quiz/sub.html
{% extends 'base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100"
                style="
        height: 697px;">
                <a href="{% url 'quiz:displaypdfai' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">AI</span></a>

                <a href="{% url 'quiz:displaypdfwt' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">WT</span> </a>

                <a href="{% url 'quiz:displaypdfos' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">OS</span></a>

                <a href="{% url 'quiz:displaypdfdm' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">DM</span></a>

                <a href="{% url 'quiz:displaypdfmccp' %}" class="nav-link px-0">
                    <span class="d-none d-sm-inline" style="color:white">MCCP</span></a>

                <hr />
            </div>
        </div>
        <div class="col py-3">Content area...</div>
    </div>
</div>
{% endblock %}